name: collect-radiation

on:
  schedule:
    # каждые 30 минут, со сдвигом на 7 минут (не совпадает с KLD)
    - cron: '7/30 * * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: collect-radiation-cy
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run collector with retry
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 10
          command: |
            set -e
            for s in collectors/radiation_collect.py radiation_collect.py scripts/collect_radiation.py; do
              if [ -f "$s" ]; then
                echo "Running: $s"
                python "$s"
                exit 0
              fi
            done
            echo "No collector script found in known locations."
            exit 1
