name: Collect SafeCast (Cyprus)

on:
  workflow_dispatch:
  schedule:
    # каждые 6 часов
    - cron: "0 */6 * * *"

permissions:
  contents: write

concurrency:
  group: safecast-cyprus
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # если у вас есть локальный модуль safecast, то:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch Safecast around Cyprus
        run: |
          python - <<'PY'
          import json, time
          from pathlib import Path

          # Координаты: НИКОСИЯ (замените при желании)
          LAT, LON = 35.1856, 33.3823
          OUT = Path("data/safecast_cyprus.json")
          OUT.parent.mkdir(parents=True, exist_ok=True)

          # Попробуем использовать ваш модуль safecast.py, если он есть
          data = None
          try:
              import safecast  # ваш модуль
              # ожидаемая функция: get_area_snapshot(lat, lon) или аналогичная
              if hasattr(safecast, "get_area_snapshot"):
                  data = safecast.get_area_snapshot(LAT, LON) or {}
              elif hasattr(safecast, "collect"):  # fallback
                  data = safecast.collect(LAT, LON) or {}
          except Exception as e:
              print("Safecast module not found/failed:", e)

          # Минимальный фоллбэк: если модуля нет — пишем пустую «заглушку» с таймстампом
          if not isinstance(data, dict) or not data:
              data = {"ts": int(time.time()), "lat": LAT, "lon": LON}

          # нормализуем ключи под ваш post_common
          data.setdefault("ts", int(time.time()))
          # Допустимые поля: pm25, pm10, cpm, radiation_usvh — если ваш сборщик их формирует.

          OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
          print("Wrote", OUT)
          PY

      - name: Commit changes (if any)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/safecast_cyprus.json || true
          if ! git diff --cached --quiet; then
            git commit -m "safecast(Cyprus): update data/safecast_cyprus.json"
            git push
          else
            echo "No changes in data/safecast_cyprus.json"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: safecast_cyprus.json
          path: data/safecast_cyprus.json
          if-no-files-found: warn
          retention-days: 3
