name: collect-radiation

on:
  schedule:
    # каждые 30 минут со сдвигом, чтобы не совпадать с другими задачами
    - cron: '4/30 * * * *'
  workflow_dispatch:

permissions:
  # нужно для коммита/пуша JSON-файлов с замерами
  contents: write

concurrency:
  group: collect-radiation-cy
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run collector with retry
        shell: bash
        run: |
          set -e
          cd "${GITHUB_WORKSPACE:?}"
          echo "PWD=$(pwd)"
          ls -la

          # до 3 попыток найти и запустить любой из известных скриптов-сборщиков
          for attempt in 1 2 3; do
            echo "::group::Attempt ${attempt}"
            for s in \
              collectors/radiation_collect.py \
              radiation_collect.py \
              scripts/collect_radiation.py
            do
              if [ -f "$s" ]; then
                echo "Running: $s"
                if python "$s"; then
                  echo "::endgroup::"
                  # Успех — выходим из обоих циклов
                  exit 0
                else
                  echo "Collector failed (attempt ${attempt})."
                fi
              fi
            done
            echo "::endgroup::"
            echo "Sleeping 10s before next attempt…"
            sleep 10
          done

          echo "No collector script found in known locations."
          exit 1

      - name: Commit data
        shell: bash
        run: |
          set -e
          cd "${GITHUB_WORKSPACE:?}"

          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "rad-bot"
          git config user.email "bot@users.noreply.github.com"

          # Добавляем файлы, которые может писать коллектор
          git add radiation_hourly.json 2>/dev/null || true
          git add data/safecast_cy.json 2>/dev/null || true
          git add data/radiation_official.json 2>/dev/null || true

          git commit -m "radiation: hourly update [cy]" || echo "no changes"
          git push
