name: collect-radiation (Cyprus)

on:
  schedule:
    # каждые 30 минут со сдвигом, чтобы не совпадать с другими джобами
    - cron: '7/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write   # нам нужно коммитить файл истории

concurrency:
  group: collect-radiation-cy
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Nicosia

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run collector
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 8
          command: |
            set -e
            # пробуем несколько возможных расположений
            for s in collectors/radiation_collect.py radiation_collect.py scripts/collect_radiation.py; do
              if [ -f "$s" ]; then
                echo "Running: $s"
                python "$s"
                exit 0
              fi
            done
            echo "No collector script found in known locations."
            exit 1

      - name: Commit updated history (if changed)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # чаще всего файл называется так (адаптируйте при необходимости):
          FILES="radiation_hourly.json data/radiation_hourly.json"
          CHANGED=0
          for f in $FILES; do
            if [ -f "$f" ]; then
              git add "$f"
              CHANGED=1
            fi
          done

          if [ "$CHANGED" -eq 1 ]; then
            if ! git diff --cached --quiet; then
              git commit -m "chore: update radiation_hourly.json (Auto)"
              git push
            else
              echo "No content changes to commit."
            fi
          else
            echo "No known radiation history files found."
          fi
