name: Collect SafeCast (Cyprus)

on:
  schedule:
    # каждые 6 часов (UTC)
    - cron: "5 */6 * * *"
  workflow_dispatch:
    inputs:
      lat:
        description: "Широта (по умолчанию Лимассол)"
        type: string
        required: false
        default: "34.707"
      lon:
        description: "Долгота (по умолчанию Лимассол)"
        type: string
        required: false
        default: "33.022"
      distance_km:
        description: "Радиус выборки, км"
        type: string
        required: false
        default: "50"
      since_hours:
        description: "Глубина истории, часов"
        type: string
        required: false
        default: "48"
      region:
        description: "Метка региона в выходном JSON"
        type: string
        required: false
        default: "Cyprus"
      file:
        description: "Путь к выходному файлу"
        type: string
        required: false
        default: "data/safecast_cy.json"
      dry_run:
        description: "Только собрать, без коммита"
        type: boolean
        required: false
        default: false

permissions:
  contents: write

concurrency:
  group: collect-safecast-cy
  cancel-in-progress: true

env:
  TZ: Asia/Nicosia
  # значения по умолчанию (могут быть переопределены inputs)
  SC_LAT: "34.707"
  SC_LON: "33.022"
  SC_DISTANCE_KM: "50"
  SC_SINCE_HOURS: "48"
  SC_REGION: "Cyprus"
  SC_FILE: "data/safecast_cy.json"
  SC_USER_AGENT: "vaybometer-cy/1.0 (+github actions)"

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (safe)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests pendulum
          fi

      - name: Export overrides from inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: |
          [ -n "${{ inputs.lat }}"          ] && echo "SC_LAT=${{ inputs.lat }}" >> $GITHUB_ENV
          [ -n "${{ inputs.lon }}"          ] && echo "SC_LON=${{ inputs.lon }}" >> $GITHUB_ENV
          [ -n "${{ inputs.distance_km }}"  ] && echo "SC_DISTANCE_KM=${{ inputs.distance_km }}" >> $GITHUB_ENV
          [ -n "${{ inputs.since_hours }}"  ] && echo "SC_SINCE_HOURS=${{ inputs.since_hours }}" >> $GITHUB_ENV
          [ -n "${{ inputs.region }}"       ] && echo "SC_REGION=${{ inputs.region }}" >> $GITHUB_ENV
          [ -n "${{ inputs.file }}"         ] && echo "SC_FILE=${{ inputs.file }}" >> $GITHUB_ENV
          echo "DRY_RUN=${{ inputs.dry_run && '1' || '' }}" >> $GITHUB_ENV

      - name: Run collector
        shell: bash
        run: |
          set -e
          mkdir -p "$(dirname "${SC_FILE}")"
          if [ -f safecast.py ]; then
            python - <<'PY'
            import os, runpy, pathlib
            # Убедимся, что каталог существует
            fp = pathlib.Path(os.environ["SC_FILE"])
            fp.parent.mkdir(parents=True, exist_ok=True)
            # Запуск модуля — он читает переменные окружения SC_*
            runpy.run_path("safecast.py", run_name="__main__")
            PY
          else
            echo "safecast.py not found — nothing to do."
          fi

      - name: Commit changes (if any)
        if: ${{ !inputs.dry_run }}
        shell: bash
        run: |
          set -e
          if git diff --quiet -- "${SC_FILE}"; then
            echo "No changes in ${SC_FILE}"
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${SC_FILE}"
          git commit -m "chore(safecast): update ${SC_REGION} dataset"
          git push
